name = "saiportfolio"
compatibility_date = "2026-06-18"
main = "@tanstack/react-start/server-entry"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
upload = { format = "service-worker", dir = "dist/client" }
